// This file will be generated by Supabase CLI
// For now, we'll create a basic structure that matches our schema

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          avatar_url: string | null;
          role: 'user' | 'admin' | 'superadmin';
          created_at: string;
        };
        Insert: {
          id?: string;
          username: string;
          avatar_url?: string | null;
          role?: 'user' | 'admin' | 'superadmin';
          created_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          avatar_url?: string | null;
          role?: 'user' | 'admin' | 'superadmin';
          created_at?: string;
        };
      };
      servers: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          is_public: boolean;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          is_public?: boolean;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          is_public?: boolean;
          created_by?: string;
          created_at?: string;
        };
      };
      server_members: {
        Row: {
          server_id: string;
          user_id: string;
          role_in_server: 'member' | 'admin';
          joined_at: string;
        };
        Insert: {
          server_id: string;
          user_id: string;
          role_in_server?: 'member' | 'admin';
          joined_at?: string;
        };
        Update: {
          server_id?: string;
          user_id?: string;
          role_in_server?: 'member' | 'admin';
          joined_at?: string;
        };
      };
      channels: {
        Row: {
          id: string;
          server_id: string;
          name: string;
          type: 'text' | 'voice' | 'announcements';
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          server_id: string;
          name: string;
          type?: 'text' | 'voice' | 'announcements';
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          server_id?: string;
          name?: string;
          type?: 'text' | 'voice' | 'announcements';
          sort_order?: number;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          channel_id: string;
          user_id: string;
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          channel_id: string;
          user_id: string;
          content: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          channel_id?: string;
          user_id?: string;
          content?: string;
          created_at?: string;
        };
      };
      courses: {
        Row: {
          id: string;
          server_id: string;
          title: string;
          description: string | null;
          level: 'beginner' | 'intermediate' | 'advanced';
          thumbnail_url: string | null;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          server_id: string;
          title: string;
          description?: string | null;
          level?: 'beginner' | 'intermediate' | 'advanced';
          thumbnail_url?: string | null;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          server_id?: string;
          title?: string;
          description?: string | null;
          level?: 'beginner' | 'intermediate' | 'advanced';
          thumbnail_url?: string | null;
          created_by?: string;
          created_at?: string;
        };
      };
      lessons: {
        Row: {
          id: string;
          course_id: string;
          title: string;
          video_url: string | null;
          duration_sec: number;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          title: string;
          video_url?: string | null;
          duration_sec?: number;
          order_index?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          course_id?: string;
          title?: string;
          video_url?: string | null;
          duration_sec?: number;
          order_index?: number;
          created_at?: string;
        };
      };
      livestreams: {
        Row: {
          id: string;
          server_id: string;
          title: string;
          status: 'scheduled' | 'live' | 'ended';
          scheduled_at: string | null;
          started_at: string | null;
          ended_at: string | null;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          server_id: string;
          title: string;
          status?: 'scheduled' | 'live' | 'ended';
          scheduled_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          server_id?: string;
          title?: string;
          status?: 'scheduled' | 'live' | 'ended';
          scheduled_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          created_by?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'user' | 'admin' | 'superadmin';
      server_member_role: 'member' | 'admin';
      channel_type: 'text' | 'voice' | 'announcements';
      course_level: 'beginner' | 'intermediate' | 'advanced';
      livestream_status: 'scheduled' | 'live' | 'ended';
    };
  };
}